# Generated by Django 5.2.12 on 2026-03-27 13:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('planned_start_date', models.DateField(verbose_name='fecha de inicio prevista')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En progreso'), ('blocked', 'Bloqueado'), ('completed', 'Completado')], default='planned', max_length=20, verbose_name='estado')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='prioridad')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['planned_start_date', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='tiempo estimado (horas)')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='fecha prevista de inicio')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='fecha prevista de fin')),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En progreso'), ('blocked', 'Bloqueada'), ('completed', 'Completada')], default='planned', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'parte de proyecto',
                'verbose_name_plural': 'partes de proyecto',
                'ordering': ['project__planned_start_date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('description', models.TextField(verbose_name='descripcion de lo realizado')),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='tiempo real invertido (horas)')),
                ('work_type', models.CharField(choices=[('project_work', 'Trabajo de proyecto'), ('external_task', 'Tarea externa'), ('interruption', 'Interrupcion'), ('maintenance', 'Mantenimiento'), ('other', 'Otros')], default='project_work', max_length=20, verbose_name='tipo de trabajo')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='planner.project', verbose_name='proyecto')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='planner.projecttask', verbose_name='parte del proyecto')),
            ],
            options={
                'verbose_name': 'registro diario',
                'verbose_name_plural': 'registros diarios',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_project_task_order'),
        ),
    ]
