# Generated by Django 5.2.12 on 2026-03-30 14:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def populate_project_estimated_hours(apps, schema_editor):
    Project = apps.get_model("planner", "Project")
    ProjectTask = apps.get_model("planner", "ProjectTask")

    for project in Project.objects.all():
        total = (
            ProjectTask.objects.filter(project_id=project.id)
            .aggregate(total=models.Sum("estimated_hours"))
            .get("total")
        )
        project.estimated_hours = total or Decimal("0.00")
        project.save(update_fields=["estimated_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['planned_start_date', 'name'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='horas estimadas'),
        ),
        migrations.RunPython(populate_project_estimated_hours, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='planned', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='horas dedicadas'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_type',
            field=models.CharField(choices=[('project_work', 'Trabajo de proyecto'), ('other_work', 'Trabajo no asociado a proyecto')], default='project_work', max_length=20, verbose_name='tipo de trabajo'),
        ),
    ]
