# Generated by Django 5.2.12 on 2026-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_project_options_remove_project_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7, verbose_name='color'),
        ),
    ]
