# Generated by Django 5.2.12 on 2026-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de entrega'),
        ),
    ]
