# Generated by Django 5.2.12 on 2026-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_project_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible en calendario'),
        ),
    ]
