# Generated by Django 5.2.12 on 2026-03-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_project_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_other_work', models.BooleanField(default=True, verbose_name='mostrar trabajo fuera de proyecto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracion del planificador',
                'verbose_name_plural': 'configuracion del planificador',
            },
        ),
    ]
