# Generated by Django 5.2.12 on 2026-03-30 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_plannersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='usuarios asignados'),
        ),
        migrations.AddField(
            model_name='project',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_projects', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuarios que realizan'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
    ]
