# Generated by Django 5.2.12 on 2026-03-30 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_project_assigned_users_project_requested_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='project',
            name='requested_by',
            field=models.ManyToManyField(blank=True, related_name='requested_projects', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='requested_by',
            field=models.ManyToManyField(blank=True, related_name='requested_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
    ]
