# Generated by Django 5.2.12 on 2026-04-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_project_requested_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('file_url', models.URLField(max_length=600, verbose_name='url del archivo')),
                ('cloudinary_public_id', models.CharField(max_length=255, verbose_name='id publico de Cloudinary')),
                ('cloudinary_resource_type', models.CharField(default='raw', max_length=50, verbose_name='tipo de recurso')),
                ('file_format', models.CharField(blank=True, max_length=50, verbose_name='formato')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='tamano en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'adjunto de proyecto',
                'verbose_name_plural': 'adjuntos de proyecto',
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('file_url', models.URLField(max_length=600, verbose_name='url del archivo')),
                ('cloudinary_public_id', models.CharField(max_length=255, verbose_name='id publico de Cloudinary')),
                ('cloudinary_resource_type', models.CharField(default='raw', max_length=50, verbose_name='tipo de recurso')),
                ('file_format', models.CharField(blank=True, max_length=50, verbose_name='formato')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='tamano en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.worklog', verbose_name='registro diario')),
            ],
            options={
                'verbose_name': 'adjunto de registro diario',
                'verbose_name_plural': 'adjuntos de registros diarios',
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
    ]
