# Generated by Django 5.2.13 on 2026-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_enable_supabase_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(db_index=True, verbose_name='fecha'),
        ),
    ]
